[build]
  publish = "."
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"